version: '1'
services:
  proxy:
    image: nginx:latest
    container_name: proxy_container
    volumes:
      - ./docker/proxy/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    networks:
      - app-network
  app:
    container_name: laravel_app_container
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www/
      - "phpsocket:/var/run"
    command:
      - php-fpm
    environment:
      - "DB_HOST=mysql"
      - "DB_USERNAME=myuser"
      - "DB_PASSWORD=mypassword"
    networks:
      - app-network
  web:
    container_name: laravel_web_container
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
      - "phpsocket:/var/run"
#    ports:
#      - "9090:80"
    networks:
      - app-network
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin 
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - app-network
    #ports:
    #  - 9091:80
networks:
  app-network:
    driver: bridge
volumes:
  phpsocket:
  mysql_data: